### ISSUE TITLE
Add cancel button during programming

### ISSUE THREAD

**Issue by panhejia** [thirtythreeforty/bullycpp#1]
Awesome work George! 
Sometimes the programming progress might get stuck, and I have no way to stop the programming process but restart the BullyCPP
![image](https://cloud.githubusercontent.com/assets/3999697/6027898/e463781c-abaa-11e4-9f8b-4e44578ac868.png)
After BullyCPP is restarted, error message "Failed to open serial port: Access is denied" is shown
![image](https://cloud.githubusercontent.com/assets/3999697/6027927/25902970-abab-11e4-9c07-b141fe0f5cc0.png)

To reproduce this error, load a hex file into BullyCPP, enable "MCLR before programming" and program. After it completes, disable "MCLR before programming", and hit "program!" again. Now the progress bar freezes. Restarting BullyCPP will show "Access denied" message. Sometimes "Retry" button won't work. The only way that I know is to replug the FTDI cable and restart BullyCPP.

Students usually either prefer to manually MCLR the PIC, or use MCLR wire from FTDI cable, they will rarely switch between these two methods. So I do not think this will be a big issue though.

**Comment by thirtythreeforty** [comment]
Yep, I've run into this issue, and you're right, you'll have to restart BullyCPP currently.  I've started working on it (involves throwing an exception from within the `programHex()` method).  This is the thing I'm holding back on for a v1.0 release.

The reason "Access is denied" is because although the old BullyCPP window is closed, the process doesn't exit because the receiver code can't exit its wait loop.  The old BullyCPP retains the lock on the COM port.  That issue will vanish when the timeout is implemented.

Thanks for the feedback!

**Comment by thirtythreeforty** [comment]
This should now be implemented; please let me know if you see any glitches.  I'll be pushing a new Windows build shortly.  Your existing copy should bother you about the update.
