### ISSUE TITLE
Hard to see that the lock button is down

### ISSUE THREAD

**Issue by thirtythreeforty** [thirtythreeforty/bullycpp#18]
The lock button should change from an unlocked padlock to a locked one.  This will make it easier to see on Windows 10, where the OS merely shades the button a little.

**Comment by vidavidorra** [comment]
I've got the source files today, since I've got the day off from school :laughing:.  
So I was playing around with the lock icon for a bit and created the icon below as unlocked padlock. I've added it to the resource file and added it to standard at the StickyQButton. So now the icon of the padlock is standard the open padlock and when pressed (the button is released) it changes to the locked padlock again.  
The only downside to this is that the unlocked padlock is 2 pixels higher that the unlocked padlock, thus resulting in the padlock is using up the complete 16 pixels in hight. Therefore I had to move the locked padlock down one pixel as well.  
So the padlock is very close to the edge of the actual button. See the example below.  
Personally I think it would look nicer if the lock was one more pixel away from the edge of the button, but that would result in a smaller lock. So I think it's better to have the lock close to the edge than to have a smaller lock. I would like to hear your thoughts about this.

#### New png files:

![lock1_closed](https://cloud.githubusercontent.com/assets/12871315/11622567/1a48601a-9cc7-11e5-8dd3-93920c47c99d.png) ![lock_open](https://cloud.githubusercontent.com/assets/12871315/11622201/e7db67ec-9cc3-11e5-8d9e-1d3c3e89778c.png)

#### Examples:

**Unlocked state**
![image](https://cloud.githubusercontent.com/assets/12871315/11622527/da5cb06e-9cc6-11e5-8456-484ee69f452a.png)
**Locked state**
![image](https://cloud.githubusercontent.com/assets/12871315/11622547/ff5a4b1a-9cc6-11e5-91bd-716ff6f6c808.png)

What do you think of it? If you like it I could do a pull request or hand over the adjusted image files and settings. Just let me know!

**Comment by thirtythreeforty** [comment]
Very nice!

I actually think you could get the best of both worlds regarding the padding by using the original image for the locked lock.  This would make the lock shift up and down when clicked, but I think that would just provide more visual feedback and look fine.

The other option is to just erase some of the pixels to indicate an unlocked lock (not making it any taller), but I like having the shackle pop up as you have it now.

If you want to open a pull request, that would be great!
