### ISSUE TITLE
Add a LineEdit textbox for lab 9

### ISSUE THREAD

**Issue by panhejia** [thirtythreeforty/bullycpp#2]
The old bullybootloader has a textbox for sequentially sending multiple chars to the COM port.
![image](https://cloud.githubusercontent.com/assets/3999697/6028344/6a9cb4ae-abae-11e4-97b6-792729844627.png)
In lab 9 we will use this functionality to see how many chars can UART buffer holds before it overflows. The Send&\n button will send the character sequence along with a newline char, while the Send button will not append a newline char. 
It would be great if we can embed this function inside the BullyCPP. BTW, BullyCPP is quite awesome already. :+1:

**Comment by thirtythreeforty** [comment]
So the reason I didn't reimplement that feature is because I don't (yet) fully understand why this little edit box is useful.  The way I always sent characters is just by typing in the serial console.  (Even though they don't echo there unless the microcontroller echoes them back, they are being sent).  The `Enter` key does what you would expect -- it sends a `\n` newline.

Can you type `1 2 3 4 5 [Enter]` in the serial console to have the same effect?

**Comment by panhejia** [comment]
If you type in `12345`, each char is sent to the port one by one with enough delay that UART can handle. If you send them simultaneously (faster than UART process speed) then UART need to use a hardware/software buffer to handle. Lab 9 is designed to test the size of the hardware buffer.
But it seems we found way to get around. We can simply copy those chars to the clipboard and paste them to BullyCPP so that BullyCPP can send those chars all at once.

**Comment by thirtythreeforty** [comment]
Ah, I see.  (It's been a while since I had that lab.)  Yep, that solution works, although it isn't mentioned in the documentation, which I will fix.  Sounds good then.  Another thing you can do is drag a file onto the serial console, and BullyCPP will transmit its contents.
