### ISSUE TITLE
Simpler MCLR

### ISSUE THREAD

**Issue by bjones1** [thirtythreeforty/bullycpp#8]
On helpful feature suggestion: could clicking the MCLR button reset the PIC (a low, then back to high pulse), rather than toggling the state of MCLR? I find it a bit hard to see graphically whether MCLR is pressed or released, and think users would expect a click to work more like a reset pushbutton.

**Comment by thirtythreeforty** [comment]
I see where you're coming from.  I implemented it this way because I often find it very useful to hold the microcontroller in reset.  Of course, it's a fairly trivial change to make the MCLR button work as a pushbutton, but I'd like to preserve that functionality.

I agree that it's a bit tough to see the button on Windows; I developed it using the native Qt5 theme Fusion, which makes it very easy to see that the button is down.  If it were easier to tell that the button is down, I think it would help with confusion as well.  However, I think a checkbox looks wrong, but that's just my opinion.

If you can think of a better paradigm, I'm open to suggestions.

**Comment by bjones1** [comment]
How long do you hold it in reset? If it's a short time, perhaps have the pushbutton act like a physical button (click and hold -> remains in reset; release -> deassert MCLR)?

I don't like a checkbox either. Radio button don't appeal, likewise. A good, well-drawn toggle button (probably the QT5 fusion theme) might express this. ???

**Comment by thirtythreeforty** [comment]
So Qt has a widget called a QToolButton that is like a button but also has
a drop down menu arrow next to it (like the kind you see in, well,
toolbars).  It might work well for this scenario to have the big MCLR work
like you say, and have the little arrow stick the big button down (like the
Shift Lock button on typewriters, if you remember those).  Clicking either
button would release them both.

I'll have to play with this; it will likely require subclassing to get it
to act just right.

How does that sound?

**Comment by bjones1** [comment]
Seems reasonable. Another suggestion: perhaps add a menu item or checkbox named "Sticky MCLR", which would change the button's behavior (and be a bit less work?)

**Comment by panhejia** [comment]
Can we just change its stylesheet? maybe color? like discussed here.
http://www.qtcentre.org/threads/46361-QPushbutton-background-color-but-flat
It might not be the best way, but changing stylesheet avoids subclassing.

**Comment by thirtythreeforty** [comment]
Hmm.  That's an idea, but what should the button look like when it's
pressed versus locked?  And how would the user trigger a lock?

**Comment by thirtythreeforty** [comment]
@bjones1 I just implemented this with the locking button I described earlier.  If it's buggy, please let me know in this or a new issue.  If everything looks good, I'm going to cut a release in a day or two.

**Comment by bjones1** [comment]
Very nice -- visually, that's quite clear. I'll do a bit more testing on my board and let you know.
